# Generated by Django 5.0.3 on 2024-03-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [""]

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pclass", models.CharField(blank=True,
                                            max_length=2,
                                            null=True)),
                ("Name", models.CharField(blank=True,
                                          max_length=200,
                                          null=True)),
                ("Sex", models.CharField(blank=True, max_length=5, null=True)),
                ("Age", models.CharField(blank=True, max_length=3, null=True)),
                ("SibSp", models.CharField(blank=True, max_length=3,
                                           null=True)),
                ("Parch", models.CharField(blank=True, max_length=1,
                                           null=True)),
                ("Ticket",
                 models.CharField(blank=True, max_length=10, null=True)),
                ("Fare", models.CharField(blank=True, max_length=20,
                                          null=True)),
                ("Cabin", models.CharField(blank=True, max_length=5,
                                           null=True)),
                ("Embarked",
                 models.CharField(blank=True, max_length=1, null=True)),
                ("Created", models.DateTimeField(auto_now_add=True)),
                ("Modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dataset",
                "verbose_name_plural": "Datasets",
            },
        ),
    ]
