# Generated by Django 5.0.3 on 2024-03-05 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_datasetfile_created_datasetfile_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingletonModel',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='datasetfile',
            name='Created',
        ),
        migrations.RemoveField(
            model_name='datasetfile',
            name='Modified',
        ),
        migrations.RemoveField(
            model_name='datasetfile',
            name='id',
        ),
        migrations.AddField(
            model_name='datasetfile',
            name='singletonmodel_ptr',
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='Main.singletonmodel'),
            preserve_default=False,
        ),
    ]
