# Generated by Django 5.0.3 on 2024-03-05 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_singletonmodel_remove_datasetfile_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singletonmodel',
            name='Created',
        ),
        migrations.RemoveField(
            model_name='singletonmodel',
            name='Modified',
        ),
    ]
